//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0 using the following command:
// xscgen --dc -0 -t Digipost.Api.Client.DataTypes.Core/Resources/XSD/datatypes.xsd -o Digipost.Api.Client.DataTypes.Core/Internal/ -n http://api.digipost.no/schema/datatypes=Digipost.Api.Client.DataTypes.Core.Internal
namespace Digipost.Api.Client.DataTypes.Core.Internal
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Address
    {
        
        [System.Xml.Serialization.XmlElementAttribute("street-address")]
        public string StreetAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("street-address-2")]
        public string StreetAddress2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("postal-code")]
        public string PostalCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("city")]
        public string City { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("country")]
        public string Country { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("appointment", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("appointment", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Appointment
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("start-time")]
        public string StartTime { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("end-time")]
        public string EndTime { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("arrival-time")]
        public string ArrivalTime { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("place")]
        public string Place { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public Address Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sub-title")]
        public string SubTitle { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Info> _info;
        
        [System.Xml.Serialization.XmlElementAttribute("info")]
        public System.Collections.ObjectModel.Collection<Info> Info
        {
            get
            {
                return _info;
            }
            private set
            {
                _info = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfoSpecified
        {
            get
            {
                return (this.Info.Count != 0);
            }
        }
        
        public Appointment()
        {
            this._info = new System.Collections.ObjectModel.Collection<Info>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Language _language = Digipost.Api.Client.DataTypes.Core.Internal.Language.Nb;
        
        [System.ComponentModel.DefaultValueAttribute(Digipost.Api.Client.DataTypes.Core.Internal.Language.Nb)]
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public Language Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public ExternalLink Link { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("info", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Info
    {
        
        [System.Xml.Serialization.XmlElementAttribute("title")]
        public string Title { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("text")]
        public string Text { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("language", Namespace="http://api.digipost.no/schema/datatypes")]
    public enum Language
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("EN")]
        En,
        
        [System.Xml.Serialization.XmlEnumAttribute("NB")]
        Nb,
        
        [System.Xml.Serialization.XmlEnumAttribute("NN")]
        Nn,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("externalLink", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("externalLink", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class ExternalLink
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("url")]
        public string Url { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("deadline", DataType="dateTime")]
        public System.DateTime DeadlineValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DeadlineValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Deadline
        {
            get
            {
                if (this.DeadlineValueSpecified)
                {
                    return this.DeadlineValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DeadlineValue = value.GetValueOrDefault();
                this.DeadlineValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("button-text")]
        public string ButtonText { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("barcode", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Barcode
    {
        
        [System.Xml.Serialization.XmlElementAttribute("barcode-value")]
        public string BarcodeValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("barcode-type")]
        public string BarcodeType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("barcode-text")]
        public string BarcodeText { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _showValueInBarcode = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlElementAttribute("show-value-in-barcode")]
        public bool ShowValueInBarcode
        {
            get
            {
                return _showValueInBarcode;
            }
            set
            {
                _showValueInBarcode = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("boligdetaljer", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("boligdetaljer", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Boligdetaljer
    {
        
        [System.Xml.Serialization.XmlElementAttribute("residence")]
        public Residence Residence { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Hjemmelshaver> _hjemmelshavere;
        
        [System.Xml.Serialization.XmlElementAttribute("hjemmelshavere")]
        public System.Collections.ObjectModel.Collection<Hjemmelshaver> Hjemmelshavere
        {
            get
            {
                return _hjemmelshavere;
            }
            private set
            {
                _hjemmelshavere = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HjemmelshavereSpecified
        {
            get
            {
                return (this.Hjemmelshavere.Count != 0);
            }
        }
        
        public Boligdetaljer()
        {
            this._hjemmelshavere = new System.Collections.ObjectModel.Collection<Hjemmelshaver>();
            this._omsetningshistorikk = new System.Collections.ObjectModel.Collection<Omsetningshistorikk>();
            this._heftelser = new System.Collections.ObjectModel.Collection<Heftelse>();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("bruksareal")]
        public int BruksarealValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool BruksarealValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Bruksareal
        {
            get
            {
                if (this.BruksarealValueSpecified)
                {
                    return this.BruksarealValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BruksarealValue = value.GetValueOrDefault();
                this.BruksarealValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("antall-oppholdsrom")]
        public int AntallOppholdsromValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AntallOppholdsromValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> AntallOppholdsrom
        {
            get
            {
                if (this.AntallOppholdsromValueSpecified)
                {
                    return this.AntallOppholdsromValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AntallOppholdsromValue = value.GetValueOrDefault();
                this.AntallOppholdsromValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("antall-baderom")]
        public int AntallBaderomValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AntallBaderomValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> AntallBaderom
        {
            get
            {
                if (this.AntallBaderomValueSpecified)
                {
                    return this.AntallBaderomValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AntallBaderomValue = value.GetValueOrDefault();
                this.AntallBaderomValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Omsetningshistorikk> _omsetningshistorikk;
        
        [System.Xml.Serialization.XmlElementAttribute("omsetningshistorikk")]
        public System.Collections.ObjectModel.Collection<Omsetningshistorikk> Omsetningshistorikk
        {
            get
            {
                return _omsetningshistorikk;
            }
            private set
            {
                _omsetningshistorikk = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OmsetningshistorikkSpecified
        {
            get
            {
                return (this.Omsetningshistorikk.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("organisasjonsnummer")]
        public string Organisasjonsnummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("bruksenhet")]
        public string Bruksenhet { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("andelsnummer")]
        public string Andelsnummer { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Heftelse> _heftelser;
        
        [System.Xml.Serialization.XmlElementAttribute("heftelser")]
        public System.Collections.ObjectModel.Collection<Heftelse> Heftelser
        {
            get
            {
                return _heftelser;
            }
            private set
            {
                _heftelser = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeftelserSpecified
        {
            get
            {
                return (this.Heftelser.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("callToAction")]
        public ExternalLink CallToAction { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Language _language = Digipost.Api.Client.DataTypes.Core.Internal.Language.Nb;
        
        [System.ComponentModel.DefaultValueAttribute(Digipost.Api.Client.DataTypes.Core.Internal.Language.Nb)]
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public Language Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("residence", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("residence", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Residence
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public ResidenceAddress Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("matrikkel")]
        public Matrikkel Matrikkel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("source")]
        public string Source { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("external-id")]
        public string ExternalId { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("residenceAddress", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResidenceAddress
    {
        
        [System.Xml.Serialization.XmlElementAttribute("unit-number")]
        public string UnitNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("house-number")]
        public string HouseNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("street-name")]
        public string StreetName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("postal-code")]
        public string PostalCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("city")]
        public string City { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("matrikkel", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Matrikkel
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("kommunenummer")]
        public string Kommunenummer { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("gaardsnummer")]
        public string Gaardsnummer { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("bruksnummer")]
        public string Bruksnummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("festenummer")]
        public string Festenummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("seksjonsnummer")]
        public string Seksjonsnummer { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("hjemmelshaver", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Hjemmelshaver
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("email")]
        public string Email { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("omsetningshistorikk", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Omsetningshistorikk
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dato")]
        public string Dato { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("beskrivelse")]
        public string Beskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("selger")]
        public string Selger { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("kjoeper")]
        public string Kjoeper { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("beloep")]
        public long BeloepValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool BeloepValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<long> Beloep
        {
            get
            {
                if (this.BeloepValueSpecified)
                {
                    return this.BeloepValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BeloepValue = value.GetValueOrDefault();
                this.BeloepValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("heftelse", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Heftelse
    {
        
        [System.Xml.Serialization.XmlElementAttribute("panthaver")]
        public string Panthaver { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("type-pant")]
        public string TypePant { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("beloep")]
        public string Beloep { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("event", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("event", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Event
    {
        
        [System.Xml.Serialization.XmlElementAttribute("sub-title")]
        public string SubTitle { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TimeInterval> _startTime;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("start-time")]
        public System.Collections.ObjectModel.Collection<TimeInterval> StartTime
        {
            get
            {
                return _startTime;
            }
            private set
            {
                _startTime = value;
            }
        }
        
        public Event()
        {
            this._startTime = new System.Collections.ObjectModel.Collection<TimeInterval>();
            this._info = new System.Collections.ObjectModel.Collection<Info>();
            this._links = new System.Collections.ObjectModel.Collection<Link>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("timeLabel")]
        public string TimeLabel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("place")]
        public string Place { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("placeLabel")]
        public string PlaceLabel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public Address Address { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Info> _info;
        
        [System.Xml.Serialization.XmlElementAttribute("info")]
        public System.Collections.ObjectModel.Collection<Info> Info
        {
            get
            {
                return _info;
            }
            private set
            {
                _info = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfoSpecified
        {
            get
            {
                return (this.Info.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("barcodeLabel")]
        public string BarcodeLabel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("barcode")]
        public Barcode Barcode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Link> _links;
        
        [System.Xml.Serialization.XmlElementAttribute("links")]
        public System.Collections.ObjectModel.Collection<Link> Links
        {
            get
            {
                return _links;
            }
            private set
            {
                _links = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinksSpecified
        {
            get
            {
                return (this.Links.Count != 0);
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public Language LanguageValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool LanguageValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<Language> Language
        {
            get
            {
                if (this.LanguageValueSpecified)
                {
                    return this.LanguageValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.LanguageValue = value.GetValueOrDefault();
                this.LanguageValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("timeInterval", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimeInterval
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("start-time")]
        public string StartTime { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("end-time")]
        public string EndTime { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("link", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Link
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("url")]
        public string Url { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("foreignCurrencyPayment", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForeignCurrencyPayment
    {
        
        [System.Xml.Serialization.XmlElementAttribute("currency-code")]
        public string CurrencyCode { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public decimal AmountValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AmountValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Amount
        {
            get
            {
                if (this.AmountValueSpecified)
                {
                    return this.AmountValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AmountValue = value.GetValueOrDefault();
                this.AmountValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("exchange-rate")]
        public decimal ExchangeRateValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ExchangeRateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> ExchangeRate
        {
            get
            {
                if (this.ExchangeRateValueSpecified)
                {
                    return this.ExchangeRateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ExchangeRateValue = value.GetValueOrDefault();
                this.ExchangeRateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("label")]
        public string Label { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("inkasso", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("inkasso", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Inkasso
    {
        
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public ExternalLink Link { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("due-date")]
        public string DueDate { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("sum")]
        public decimal SumValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SumValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Sum
        {
            get
            {
                if (this.SumValueSpecified)
                {
                    return this.SumValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SumValue = value.GetValueOrDefault();
                this.SumValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("account")]
        public string Account { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("kid")]
        public string Kid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("payslip", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("payslip", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Payslip
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("signedDocument", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("signedDocument", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class SignedDocument
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("document-issuer")]
        public string DocumentIssuer { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("document-subject")]
        public string DocumentSubject { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("signing-time")]
        public string SigningTime { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("bank", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Bank
    {
        
        [System.Xml.Serialization.XmlElementAttribute("id")]
        public string Id { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("invoice", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("invoice", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Invoice
    {
        
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public ExternalLink Link { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("due-date")]
        public string DueDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("sum")]
        public decimal Sum { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("creditor-account")]
        public string CreditorAccount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("kid")]
        public string Kid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("invoicePayment", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("invoice-payment", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class InvoicePayment
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("payment-id")]
        public string PaymentId { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("payment-status")]
        public string PaymentStatus { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("payment-time")]
        public string PaymentTime { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("debtor-account")]
        public string DebtorAccount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("debtor-account-name")]
        public string DebtorAccountName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("payment-channel")]
        public string PaymentChannel { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("payment-bank")]
        public Bank PaymentBank { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("cost", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cost
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value-to-be-payed")]
        public decimal ValueToBePayed { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("package-value")]
        public decimal PackageValueValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool PackageValueValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> PackageValue
        {
            get
            {
                if (this.PackageValueValueSpecified)
                {
                    return this.PackageValueValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.PackageValueValue = value.GetValueOrDefault();
                this.PackageValueValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("customs-fee-outlayed")]
        public decimal CustomsFeeOutlayedValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CustomsFeeOutlayedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> CustomsFeeOutlayed
        {
            get
            {
                if (this.CustomsFeeOutlayedValueSpecified)
                {
                    return this.CustomsFeeOutlayedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CustomsFeeOutlayedValue = value.GetValueOrDefault();
                this.CustomsFeeOutlayedValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("vas-text")]
        public string VasText { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("customs-fee")]
        public decimal CustomsFeeValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CustomsFeeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> CustomsFee
        {
            get
            {
                if (this.CustomsFeeValueSpecified)
                {
                    return this.CustomsFeeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CustomsFeeValue = value.GetValueOrDefault();
                this.CustomsFeeValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("customs-fee-outlay-cost")]
        public decimal CustomsFeeOutlayCostValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CustomsFeeOutlayCostValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> CustomsFeeOutlayCost
        {
            get
            {
                if (this.CustomsFeeOutlayCostValueSpecified)
                {
                    return this.CustomsFeeOutlayCostValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CustomsFeeOutlayCostValue = value.GetValueOrDefault();
                this.CustomsFeeOutlayCostValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("cod-amount")]
        public decimal CodAmountValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CodAmountValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> CodAmount
        {
            get
            {
                if (this.CodAmountValueSpecified)
                {
                    return this.CodAmountValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CodAmountValue = value.GetValueOrDefault();
                this.CodAmountValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("cod-fee")]
        public decimal CodFeeValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CodFeeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> CodFee
        {
            get
            {
                if (this.CodFeeValueSpecified)
                {
                    return this.CodFeeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CodFeeValue = value.GetValueOrDefault();
                this.CodFeeValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("package", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Package
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("length")]
        public int LengthValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool LengthValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Length
        {
            get
            {
                if (this.LengthValueSpecified)
                {
                    return this.LengthValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.LengthValue = value.GetValueOrDefault();
                this.LengthValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("width")]
        public int WidthValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool WidthValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Width
        {
            get
            {
                if (this.WidthValueSpecified)
                {
                    return this.WidthValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.WidthValue = value.GetValueOrDefault();
                this.WidthValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("height")]
        public int HeightValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool HeightValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Height
        {
            get
            {
                if (this.HeightValueSpecified)
                {
                    return this.HeightValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.HeightValue = value.GetValueOrDefault();
                this.HeightValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("weight")]
        public int WeightValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool WeightValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Weight
        {
            get
            {
                if (this.WeightValueSpecified)
                {
                    return this.WeightValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.WeightValue = value.GetValueOrDefault();
                this.WeightValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("pickupNotice", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("pickup-notice", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class PickupNotice
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("parcel-id")]
        public string ParcelId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("parcel-uuid")]
        public string ParcelUuid { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("barcode")]
        public Barcode Barcode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("product-name")]
        public string ProductName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("arrival-date-time")]
        public string ArrivalDateTime { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("return-date-time")]
        public string ReturnDateTime { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("recipient")]
        public Recipient Recipient { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sender")]
        public Sender Sender { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pickup-place")]
        public PickupPlace PickupPlace { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("package")]
        public Package Package { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cost")]
        public Cost Cost { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("status")]
        public Status StatusValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool StatusValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<Status> Status
        {
            get
            {
                if (this.StatusValueSpecified)
                {
                    return this.StatusValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.StatusValue = value.GetValueOrDefault();
                this.StatusValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Tag> _tags;
        
        [System.Xml.Serialization.XmlElementAttribute("tags")]
        public System.Collections.ObjectModel.Collection<Tag> Tags
        {
            get
            {
                return _tags;
            }
            private set
            {
                _tags = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TagsSpecified
        {
            get
            {
                return (this.Tags.Count != 0);
            }
        }
        
        public PickupNotice()
        {
            this._tags = new System.Collections.ObjectModel.Collection<Tag>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Language _language = Digipost.Api.Client.DataTypes.Core.Internal.Language.Nb;
        
        [System.ComponentModel.DefaultValueAttribute(Digipost.Api.Client.DataTypes.Core.Internal.Language.Nb)]
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public Language Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public ExternalLink Link { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("recipient", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Recipient
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("digipost-address")]
        public string DigipostAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public Address Address { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("sender", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sender
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("reference")]
        public string Reference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public Address Address { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("pickupPlace", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PickupPlace
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("code")]
        public string Code { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("instruction")]
        public string Instruction { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("shelf-location")]
        public string ShelfLocation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public Address Address { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("status", Namespace="http://api.digipost.no/schema/datatypes")]
    public enum Status
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("DEVIATION")]
        Deviation,
        
        [System.Xml.Serialization.XmlEnumAttribute("READY_FOR_PICKUP")]
        ReadyForPickup,
        
        [System.Xml.Serialization.XmlEnumAttribute("RETURNED")]
        Returned,
        
        [System.Xml.Serialization.XmlEnumAttribute("PICKED_UP")]
        PickedUp,
        
        [System.Xml.Serialization.XmlEnumAttribute("UNKNOWN")]
        Unknown,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tag", Namespace="http://api.digipost.no/schema/datatypes")]
    public enum Tag
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("VARSEL1")]
        Varsel1,
        
        [System.Xml.Serialization.XmlEnumAttribute("VARSEL2")]
        Varsel2,
        
        [System.Xml.Serialization.XmlEnumAttribute("POSTEN")]
        Posten,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("pickupNoticeStatus", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("pickup-notice-status", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class PickupNoticeStatus
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("status")]
        public Status Status { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("occurrence-datetime")]
        public string OccurrenceDatetime { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("calendarDate", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalendarDate
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("month")]
        public int Month { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("day")]
        public int Day { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _hour = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlElementAttribute("hour")]
        public int Hour
        {
            get
            {
                return _hour;
            }
            set
            {
                _hour = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _min = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlElementAttribute("min")]
        public int Min
        {
            get
            {
                return _min;
            }
            set
            {
                _min = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _timeZone = "+01:00";
        
        [System.ComponentModel.DefaultValueAttribute("+01:00")]
        [System.Xml.Serialization.XmlElementAttribute("time-zone")]
        public string TimeZone
        {
            get
            {
                return _timeZone;
            }
            set
            {
                _timeZone = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("period", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Period
    {
        
        [System.Xml.Serialization.XmlElementAttribute("from")]
        public string From { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("to")]
        public string To { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("proof", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("proof", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Proof
    {
        
        [System.Xml.Serialization.XmlElementAttribute("authorizer-name")]
        public string AuthorizerName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("background-color")]
        public string BackgroundColor { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("issued-time")]
        public string IssuedTime { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("valid-period")]
        public ValidPeriod ValidPeriod { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("proof-holder")]
        public ProofHolder ProofHolder { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("title")]
        public string Title { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("proof-id-name")]
        public string ProofIdName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("proof-id-value")]
        public string ProofIdValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Info> _attribute;
        
        [System.Xml.Serialization.XmlElementAttribute("attribute")]
        public System.Collections.ObjectModel.Collection<Info> Attribute
        {
            get
            {
                return _attribute;
            }
            private set
            {
                _attribute = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AttributeSpecified
        {
            get
            {
                return (this.Attribute.Count != 0);
            }
        }
        
        public Proof()
        {
            this._attribute = new System.Collections.ObjectModel.Collection<Info>();
            this._info = new System.Collections.ObjectModel.Collection<Info>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Info> _info;
        
        [System.Xml.Serialization.XmlElementAttribute("info")]
        public System.Collections.ObjectModel.Collection<Info> Info
        {
            get
            {
                return _info;
            }
            private set
            {
                _info = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfoSpecified
        {
            get
            {
                return (this.Info.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Language _language = Digipost.Api.Client.DataTypes.Core.Internal.Language.Nb;
        
        [System.ComponentModel.DefaultValueAttribute(Digipost.Api.Client.DataTypes.Core.Internal.Language.Nb)]
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public Language Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("validPeriod", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidPeriod
    {
        
        [System.Xml.Serialization.XmlElementAttribute("period")]
        public Period Period { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("yearly-repeating-period")]
        public YearlyRepeatingPeriod YearlyRepeatingPeriod { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("yearlyRepeatingPeriod", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YearlyRepeatingPeriod
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("start-year")]
        public int StartYearValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool StartYearValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> StartYear
        {
            get
            {
                if (this.StartYearValueSpecified)
                {
                    return this.StartYearValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.StartYearValue = value.GetValueOrDefault();
                this.StartYearValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("end-year")]
        public int EndYearValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool EndYearValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> EndYear
        {
            get
            {
                if (this.EndYearValueSpecified)
                {
                    return this.EndYearValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EndYearValue = value.GetValueOrDefault();
                this.EndYearValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("from")]
        public CalendarDate From { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("to")]
        public CalendarDate To { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("proofHolder", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProofHolder
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("firstname")]
        public string Firstname { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("surname")]
        public string Surname { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("social-security-number")]
        public string SocialSecurityNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public Address Address { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("customer", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Customer
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public Address Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("phoneNumber")]
        public string PhoneNumber { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("delivery", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delivery
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public Address Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("terms")]
        public string Terms { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("payment", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Payment
    {
        
        [System.Xml.Serialization.XmlElementAttribute("type")]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("card-number")]
        public string CardNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cardName")]
        public string CardName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public string Amount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("currency-code")]
        public string CurrencyCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("foreign-currency-payment")]
        public ForeignCurrencyPayment ForeignCurrencyPayment { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("receipt", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("receipt", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Receipt
    {
        
        [System.Xml.Serialization.XmlElementAttribute("receiptId")]
        public string ReceiptId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("receiptNumber")]
        public string ReceiptNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("purchaseTime")]
        public string PurchaseTime { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("totalPrice")]
        public string TotalPrice { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("totalVat")]
        public string TotalVat { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("currency")]
        public string Currency { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cashier")]
        public string Cashier { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("register")]
        public string Register { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("merchant-chain")]
        public string MerchantChain { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("merchant-name")]
        public string MerchantName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("merchant-phone-number")]
        public string MerchantPhoneNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("merchant-address")]
        public Address MerchantAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("orgnumber")]
        public string Orgnumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("barcode")]
        public Barcode Barcode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Payment> _payments;
        
        [System.Xml.Serialization.XmlElementAttribute("payments")]
        public System.Collections.ObjectModel.Collection<Payment> Payments
        {
            get
            {
                return _payments;
            }
            private set
            {
                _payments = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentsSpecified
        {
            get
            {
                return (this.Payments.Count != 0);
            }
        }
        
        public Receipt()
        {
            this._payments = new System.Collections.ObjectModel.Collection<Payment>();
            this._items = new System.Collections.ObjectModel.Collection<ReceiptLine>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ReceiptLine> _items;
        
        [System.Xml.Serialization.XmlElementAttribute("items")]
        public System.Collections.ObjectModel.Collection<ReceiptLine> Items
        {
            get
            {
                return _items;
            }
            private set
            {
                _items = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemsSpecified
        {
            get
            {
                return (this.Items.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("taxiDetails")]
        public TaxiDetails TaxiDetails { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customer")]
        public Customer Customer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("delivery")]
        public Delivery Delivery { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("order-number")]
        public string OrderNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("membership-number")]
        public string MembershipNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("comment")]
        public string Comment { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Language _language = Digipost.Api.Client.DataTypes.Core.Internal.Language.Nb;
        
        [System.ComponentModel.DefaultValueAttribute(Digipost.Api.Client.DataTypes.Core.Internal.Language.Nb)]
        [System.Xml.Serialization.XmlElementAttribute("language")]
        public Language Language
        {
            get
            {
                return _language;
            }
            set
            {
                _language = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("receiptLine", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiptLine
    {
        
        [System.Xml.Serialization.XmlElementAttribute("item-name")]
        public string ItemName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("item-description")]
        public string ItemDescription { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("item-code")]
        public string ItemCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("unit")]
        public string Unit { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("quantity")]
        public double Quantity { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("item-price")]
        public string ItemPrice { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("item-vat")]
        public string ItemVat { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("total-price")]
        public string TotalPrice { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("total-vat")]
        public string TotalVat { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("discount")]
        public string Discount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("serialNumber")]
        public string SerialNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("eanCode")]
        public string EanCode { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("taxiDetails", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaxiDetails
    {
        
        [System.Xml.Serialization.XmlElementAttribute("carPlateNumber")]
        public string CarPlateNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("license")]
        public string License { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("orgNumberLicenseHolder")]
        public string OrgNumberLicenseHolder { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("startTime")]
        public string StartTime { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stopTime")]
        public string StopTime { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("tips")]
        public string Tips { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("totalMeterPrice")]
        public string TotalMeterPrice { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalDistanceBeforeBoardingInMeters")]
        public int TotalDistanceBeforeBoardingInMetersValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalDistanceBeforeBoardingInMetersValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalDistanceBeforeBoardingInMeters
        {
            get
            {
                if (this.TotalDistanceBeforeBoardingInMetersValueSpecified)
                {
                    return this.TotalDistanceBeforeBoardingInMetersValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalDistanceBeforeBoardingInMetersValue = value.GetValueOrDefault();
                this.TotalDistanceBeforeBoardingInMetersValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalDistanceInMeters")]
        public int TotalDistanceInMetersValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalDistanceInMetersValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalDistanceInMeters
        {
            get
            {
                if (this.TotalDistanceInMetersValueSpecified)
                {
                    return this.TotalDistanceInMetersValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalDistanceInMetersValue = value.GetValueOrDefault();
                this.TotalDistanceInMetersValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalDistanceWithPassengerInMeters")]
        public int TotalDistanceWithPassengerInMetersValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalDistanceWithPassengerInMetersValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalDistanceWithPassengerInMeters
        {
            get
            {
                if (this.TotalDistanceWithPassengerInMetersValueSpecified)
                {
                    return this.TotalDistanceWithPassengerInMetersValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalDistanceWithPassengerInMetersValue = value.GetValueOrDefault();
                this.TotalDistanceWithPassengerInMetersValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalTimeBeforeBoardingInSeconds")]
        public int TotalTimeBeforeBoardingInSecondsValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalTimeBeforeBoardingInSecondsValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalTimeBeforeBoardingInSeconds
        {
            get
            {
                if (this.TotalTimeBeforeBoardingInSecondsValueSpecified)
                {
                    return this.TotalTimeBeforeBoardingInSecondsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalTimeBeforeBoardingInSecondsValue = value.GetValueOrDefault();
                this.TotalTimeBeforeBoardingInSecondsValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalTimeInSeconds")]
        public int TotalTimeInSecondsValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalTimeInSecondsValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalTimeInSeconds
        {
            get
            {
                if (this.TotalTimeInSecondsValueSpecified)
                {
                    return this.TotalTimeInSecondsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalTimeInSecondsValue = value.GetValueOrDefault();
                this.TotalTimeInSecondsValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalTimeWithPassengerInSeconds")]
        public int TotalTimeWithPassengerInSecondsValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalTimeWithPassengerInSecondsValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalTimeWithPassengerInSeconds
        {
            get
            {
                if (this.TotalTimeWithPassengerInSecondsValueSpecified)
                {
                    return this.TotalTimeWithPassengerInSecondsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalTimeWithPassengerInSecondsValue = value.GetValueOrDefault();
                this.TotalTimeWithPassengerInSecondsValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("vat")]
        public VatDetails Vat { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("vatDetails", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VatDetails
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<VatLevel> _levels;
        
        [System.Xml.Serialization.XmlElementAttribute("levels")]
        public System.Collections.ObjectModel.Collection<VatLevel> Levels
        {
            get
            {
                return _levels;
            }
            private set
            {
                _levels = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LevelsSpecified
        {
            get
            {
                return (this.Levels.Count != 0);
            }
        }
        
        public VatDetails()
        {
            this._levels = new System.Collections.ObjectModel.Collection<VatLevel>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("sum")]
        public string Sum { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("vatLevel", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VatLevel
    {
        
        [System.Xml.Serialization.XmlElementAttribute("grossAmount")]
        public string GrossAmount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("netAmount")]
        public string NetAmount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("vat")]
        public string Vat { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("vatPercent")]
        public string VatPercent { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("shareDocumentsRequest", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("share-documents-request", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class ShareDocumentsRequest
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("max-share-duration-seconds")]
        public long MaxShareDurationSeconds { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("purpose")]
        public string Purpose { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("shareDocumentsRequestDocumentsShared", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("share-documents-request-documents-shared", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class ShareDocumentsRequestDocumentsShared
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<long> _documentIds;
        
        [System.Xml.Serialization.XmlElementAttribute("document-ids")]
        public System.Collections.ObjectModel.Collection<long> DocumentIds
        {
            get
            {
                return _documentIds;
            }
            private set
            {
                _documentIds = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentIdsSpecified
        {
            get
            {
                return (this.DocumentIds.Count != 0);
            }
        }
        
        public ShareDocumentsRequestDocumentsShared()
        {
            this._documentIds = new System.Collections.ObjectModel.Collection<long>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("shareDocumentsRequestSharingStopped", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("share-documents-request-sharing-stopped", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class ShareDocumentsRequestSharingStopped
    {
    }
}
