name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: digipost/set-timezone@v2.0
      with:
        timezoneLinux: "Europe/Oslo"

    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        cache: true
    - name: Print openssl version
      run: |
        openssl version
    - name: Decrypt signing key to use for strong-name
      env:
        SIGNINGKEY_ENC_PASSWORD: ${{ secrets.signingkeyEncPassword }}
      run: |
        openssl aes-256-cbc -salt -pbkdf2 -k "$SIGNINGKEY_ENC_PASSWORD" -in signingkey.snk.enc -out signingkey.snk -d
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Set release version
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
    - name: Set assembly version to major semver
      run: echo "ASSEMBLY_VERSION=$(echo ${GITHUB_REF:10} | cut -d '.' -f 1).0.0" >> $GITHUB_ENV
    - name: Print assembly version
      run: echo $ASSEMBLY_VERSION
    - name: Pack nupkg
      run: dotnet pack -p:PackageVersion=$RELEASE_VERSION -p:AssemblyVersion=$ASSEMBLY_VERSION --configuration Release --no-build --output digipost/packed Digipost.Api.Client.DataTypes.Core
    - name: Push to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.nugetApiKey }}
      run: dotnet nuget push digipost/packed/ --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
